apiVersion: v1
kind: Service
metadata:
  name: my-hello-world-svc
  labels:
    app: hello-world
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: hello-world
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-hello-world
  labels:
    app: hello-world
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: evantage/hello-rancher:latest
        ports:
        - containerPort: 80
